steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '--no-cache', '-t', 'europe-west1-docker.pkg.dev/tibyan-ml-core/cloud-run-source-deploy/tibyan-backend:latest', '.']
images:
- 'europe-west1-docker.pkg.dev/tibyan-ml-core/cloud-run-source-deploy/tibyan-backend:latest'
